local PAY_ONLINE_2P = "PayOnLine_2p"
local AUTHORIZE_2P = "Authorize_2p"
local QUERY_TXS = "QueryTxs"
local SIMPLE_QUERY_TX = "SimpleQueryTx"
local REFUND = "Refund"
local CAPTURE = "Capture"
local AUTHORIZE_3P = "Authorize_3p"
local BANK_PAYMENT_3P = "BankPayment_3p"
local CASH_PAYMENT_3P = "CashPayment_3p"
local CHANGE_SECRET_KEY = "ChangeSecretKey"
local FRAUD_SCREENING = "FraudScreening"
local NOTIFY_FRAUD_SCREENING_REVIEW = "NotifyFraudScreeningReview"
local PAY_ONLINE_3P = "PayOnLine_3p"
local SPLIT_AUTHORIZE_3P = "SplitAuthorize_3p"
local SPLIT_PAY_ONLINE_3P = "SplitPayOnLine_3p"
local BANK_PAYMENT_2P = "BankPayment_2p"
local SPLIT_PAY_ONLINE_2P = "SplitPayOnLine_2p"
local SPLIT_AUTHORIZE_2P = "SplitAuthorize_2p"
local QUERY_CARD_NUMBER = "QueryCardNumber"
local QUERY_CARD_DETAILS = "QueryCardDetails"
local GET_IIN_DETAILS = "GetIINDetails"
local CREATE_PAYMENT_METHOD = "CreatePaymentMethod"
local CREATE_PAYMENT_METHOD_FROM_PAYMENT = "CreatePaymentMethodFromPayment"
local RETRIEVE_PAYMENT_METHOD = "RetrievePaymentMethod"
local UPDATE_PAYMENT_METHOD = "UpdatePaymentMethod"
local DELETE_PAYMENT_METHOD = "DeletePaymentMethod"
local CREATE_CUSTOMER = "CreateCustomer"
local RETRIEVE_CUSTOMER = "RetrieveCustomer"
local UPDATE_CUSTOMER = "UpdateCustomer"
local DELETE_CUSTOMER = "DeleteCustomer"
local RECACHE_PAYMENT_METHOD_TOKEN = "RecachePaymentMethodToken"
local CREATE_PAYMENT_METHOD_TOKEN = "CreatePaymentMethodToken"
local RETRIEVE_PAYMENT_METHOD_TOKEN = "RetrievePaymentMethodToken"
local CREATE_CLIENT_SESSION = "CreateClientSession"
local GET_INSTALLMENTS_OPTIONS = "GetInstallmentsOptions"
local GET_MERCH_DET_NOT_ADD_SERVICES = {
    QUERY_TXS,
    REFUND,
    SIMPLE_QUERY_TX,
    CAPTURE,
    CHANGE_SECRET_KEY,
    NOTIFY_FRAUD_SCREENING_REVIEW,
    GET_IIN_DETAILS,
    QUERY_CARD_NUMBER,
    CREATE_PAYMENT_METHOD,
    CREATE_PAYMENT_METHOD_FROM_PAYMENT,
    RETRIEVE_PAYMENT_METHOD,
    UPDATE_PAYMENT_METHOD,
    DELETE_PAYMENT_METHOD,
    CREATE_CUSTOMER,
    RETRIEVE_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    RECACHE_PAYMENT_METHOD_TOKEN,
    CREATE_PAYMENT_METHOD_TOKEN,
    RETRIEVE_PAYMENT_METHOD_TOKEN,
    CREATE_CLIENT_SESSION,
    GET_INSTALLMENTS_OPTIONS,
    QUERY_CARD_DETAILS
}
local METHODS_WITHOUT_SECURE_HASH = {
    RETRIEVE_PAYMENT_METHOD_TOKEN,
    CREATE_PAYMENT_METHOD_TOKEN,
    RECACHE_PAYMENT_METHOD_TOKEN
}

local services = {}
services.__index = services

services.PAY_ONLINE_2P = PAY_ONLINE_2P
services.AUTHORIZE_2P = AUTHORIZE_2P
services.QUERY_TXS = QUERY_TXS
services.SIMPLE_QUERY_TX = SIMPLE_QUERY_TX
services.REFUND = REFUND
services.CAPTURE = CAPTURE
services.AUTHORIZE_3P = AUTHORIZE_3P
services.BANK_PAYMENT_3P = BANK_PAYMENT_3P
services.CASH_PAYMENT_3P = CASH_PAYMENT_3P
services.CHANGE_SECRET_KEY = CHANGE_SECRET_KEY
services.FRAUD_SCREENING = FRAUD_SCREENING
services.NOTIFY_FRAUD_SCREENING_REVIEW = NOTIFY_FRAUD_SCREENING_REVIEW
services.PAY_ONLINE_3P = PAY_ONLINE_3P
services.SPLIT_AUTHORIZE_3P = SPLIT_AUTHORIZE_3P
services.SPLIT_PAY_ONLINE_3P = SPLIT_PAY_ONLINE_3P
services.BANK_PAYMENT_2P = BANK_PAYMENT_2P
services.SPLIT_PAY_ONLINE_2P = SPLIT_PAY_ONLINE_2P
services.SPLIT_AUTHORIZE_2P = SPLIT_AUTHORIZE_2P
services.QUERY_CARD_NUMBER = QUERY_CARD_NUMBER
services.QUERY_CARD_DETAILS = QUERY_CARD_DETAILS
services.GET_IIN_DETAILS = GET_IIN_DETAILS
services.CREATE_PAYMENT_METHOD = CREATE_PAYMENT_METHOD
services.CREATE_PAYMENT_METHOD_FROM_PAYMENT = CREATE_PAYMENT_METHOD_FROM_PAYMENT
services.RETRIEVE_PAYMENT_METHOD = RETRIEVE_PAYMENT_METHOD
services.UPDATE_PAYMENT_METHOD = UPDATE_PAYMENT_METHOD
services.DELETE_PAYMENT_METHOD = DELETE_PAYMENT_METHOD
services.CREATE_CUSTOMER = CREATE_CUSTOMER
services.RETRIEVE_CUSTOMER = RETRIEVE_CUSTOMER
services.UPDATE_CUSTOMER = UPDATE_CUSTOMER
services.DELETE_CUSTOMER = DELETE_CUSTOMER
services.RECACHE_PAYMENT_METHOD_TOKEN = RECACHE_PAYMENT_METHOD_TOKEN
services.CREATE_PAYMENT_METHOD_TOKEN = CREATE_PAYMENT_METHOD_TOKEN
services.RETRIEVE_PAYMENT_METHOD_TOKEN = RETRIEVE_PAYMENT_METHOD_TOKEN
services.CREATE_CLIENT_SESSION = CREATE_CLIENT_SESSION
services.GET_INSTALLMENTS_OPTIONS = GET_INSTALLMENTS_OPTIONS
services.GET_MERCH_DET_NOT_ADD_SERVICES = GET_MERCH_DET_NOT_ADD_SERVICES
services.METHODS_WITHOUT_SECURE_HASH = METHODS_WITHOUT_SECURE_HASH

return services

